### ISSUE TITLE
Implement label search menu

### ISSUE THREAD

**Issue by LaurenceTews** [rabidgremlin/Concord#10]
Add a search menu that searches through all possible labels.

**Comment by rabidgremlin** [comment]
Yep. Maybe implement after the 1.0 release.

**Comment by LaurenceTews** [comment]
Do we have a way to add a label outside of the suggested ones until then?

**Comment by rabidgremlin** [comment]
Nope :( User will just have to use the "skip" option. Same goes with in place editing of phrase.
