### ISSUE TITLE
Realtime scores view

### ISSUE THREAD

**Issue by wilmol** [rabidgremlin/Concord#38]
In the UI, display the user scores in real time.

Either in another page or on the same page as the labeling process.

This will solve the problem of needing to make SQL queries just to view the scores.

**Comment by bstee615** [comment]
I tried to set up the project to work on this issue, but after trying to populate the RASA server with curl (step 2b in your readme) it failed with Connection Refused. I'd like to help out with this issue. Any idea why this problem is happening?

**Comment by wilmol** [comment]
@bstee615 its great you want to help us!

To solve this I think embedding the results on the label suggesting page would be best.

Then do the SQL query each time the page loads (not quite real time, but we are loading the page often).

I.e. put these results:
![conemu64_py4wf4un9i](https://user-images.githubusercontent.com/18110897/53446836-bfced300-3a78-11e9-9c1c-b40f82938334.png)

Onto this page:
![palemoon_gqnog2l1g6](https://user-images.githubusercontent.com/18110897/53446853-c52c1d80-3a78-11e9-88bf-b6f729c99772.png)

The SQL query is: 
```
select count(*) votesMade, userId from votes group by userId order by votesMade desc;
```

We are using react for the frontend.

---
As for your problem;
I can only think it being a proxy issue (it is trying to connect to localhost, dont use any proxies).
Or you aren't in the root directory (its using /testbed directory to get the data).

If it still doesn't work you can just use the ```AllLabelSuggester```, edit server.yml file to use this instead.

**Comment by wilmol** [comment]
If the problem persists can you raise as a separate issue? Thanks

**Comment by wilmol** [comment]
To start with; we can just make an endpoint (e.g. /api/votes/scores) that does that SQL query.

Then on front end print results to console.log.

**Comment by rabidgremlin** [comment]
@bstee615 @wilmol I think it might be better to show the results on a separate page using a "Drawer" component and a "hamburger" icon in the "Toolbar. See https://jamesmfriedman.github.io/rmwc/drawers for more info.

As @wilmol said, I first step is getting the API endpoint in place :)

**Comment by bstee615** [comment]
@wilmol I've been trying it on and off - can't find the issue. Here's what I get from cURL:
```
$ sudo curl -XPOST --header "Content-Type: application/json" http://localhost:5000/train?project=taxibot -d @testbed/taxibotdata.json
curl: (7) Failed to connect to localhost port 5000: Connection refused
```
Any help getting set up would be appreciated - I still want to help out because this seems like an interesting project. I also understand if you don't want to spend the time setting me up. 👍
