### ISSUE TITLE
Complete consensus logic 

### ISSUE THREAD

**Issue by rabidgremlin** [rabidgremlin/Concord#8]
Need to complete consensus logic used in PhrasesResource.downloadCsv()

Need to:

- Pull logic into other class so it can be reused by other endpoints
- Make number of votes required for consensus configurable in server.yml (consensus level)
- Only return labelled phrases for phrases that have "consensus level" more votes for one label then any other label
- Make downloaded phrases as "completed"
- Make sure all updates are in a DB transaction

**Comment by LaurenceTews** [comment]
picking up this
